### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by daKmoR** [microsoft/typescript-lit-html-plugin#34]
hey there 👋

it would be awesome if the `html` highlighting would work for `js` blocks inside markdown as well.
Here is the use case that we are after - Screenshot from VS Code

![Screenshot 2020-02-03 at 21 44 06](https://user-images.githubusercontent.com/24378/73689634-f6708d00-46ce-11ea-934d-5c93c8162695.png)

would be awesome if that is highlighted 👍 

any chance we can get some pointers on where to start looking to get this supported? e.g. we can contribute but we probably need a little help to get started 🤗

**Comment by daKmoR** [comment]
friendly reminder for these questions 🤗

- is this something you would consider? 
- if so how can we help? 
- any pointers?

**Comment by mjbvz** [comment]
This repo doesn't actually provide any syntax highlighting; that all lives in the VS Code extension: https://github.com/mjbvz/vscode-lit-html

Can you please move the issue over there. To answer your questions:

Yes, please submit a PR. The fix is to update the [injection selectors](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) for the grammar to also target html in markdown files

**Comment by rubensa** [comment]
@mjbvz Should this enable **HTML** syntax highlighting and validation for **HTML** tags inside any **markdown** part (not only inside code blocks)? :confused:

We use:

```html
    <details>
    <summary></summary>
    </details>
```
**HTML** tags pattern in many GitHub **md** files but, as **HTML** syntax is not validated inside **md** files, people tends to forget the closing `details` tag.
